### ISSUE TITLE
Make GT Scheduler more friendly for open source contribution!

### ISSUE THREAD

**Issue by karpawich** [gt-scheduler/website#33]
This repo is already quite friendly to open source contribution, but I think we can do even better! Suggested additions include:

- [ ] Issue & PR templates (see [example](https://github.com/hack4impact/slack-bot/tree/master/.github))
- [ ] `CONTRIBUTING.md` (see [example](https://github.com/hack4impact/slack-bot/blob/master/CONTRIBUTING.md))
- [ ] `CODE_OF_CONDUCT.md` (custom, not pure template!)

Many of the suggested changes above can also be applied to the other two repos:
- [ ] [crawler](https://github.com/gt-scheduler/crawler/issues/1)
- [ ] [ backend](https://github.com/gt-scheduler/backend/issues/8)

If you can think of others, please comment them, and I can add them to the Issue! I'll open a PR to get things started.
